config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :lists, only: [:new, :create, :show, :destroy] do
    # get '/lists/:id/bookmarks/new', to: 'bookmarks#new', as: 'new_bookmark'
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy


  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = List.find(params[:list_id])
    @bookmark.save!

    redirect_to list_path(params[:list_id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(params[:list_id])
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.includes(:bookmarks).all
  end

  def new
    @list = List.new
    # @list = @list.build
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = @list.bookmarks
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list.id)
    # @review = @list.build(list_params)
    # @review.list_id = @list.id
    # if @list.save
    #   redirect_to list_path(@list.id), notice: 'Review was successfully created'
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to list_path(@list)
  end

private

  def list_params
    params.require(:list).permit(:name, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="col-8 mx-auto">
  <h1>Create a bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment, class: "form-control" %>
  <%= f.submit %>
<% end %>
  <%= link_to "Back to the list", list_path(@list.id) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="col-12 mx-auto">
<img style="background-position:cover;" src="https://nextbestpicture-com.b-cdn.net/wp-content/uploads/2023/05/Midnight-In-Paris.jpg" width="100%" height="400px"alt="">
</div>
<div class="mt-3 col-8 mx-auto">
<div class="navbar d-flex justify-content-between">
  <h1>All lists</h1>
  <%= link_to new_list_path do%>
    <button class="btn btn-primary">Create a list</button>
  <% end %>
  </div>


  <% @lists.each do |list| %>
  <div class="card mt-2">
    <div class="p-3 d-flex justify-content-between">
    <div>
     <h2><%= list.name.capitalize %></h2>
     <p>- <%= list.details.capitalize %></p>
     <% list.bookmarks.each do |bookmark| %>
      <img class="rounded-circle" height="50px" width="50px" src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title%>">
      <% end %>
      <div class="mt-3">
     <%= link_to list_path(list.id) do %>
      <button class="btn btn-success rounded text-white">View</button>
    <% end %>
    </div>
     </div>

      <%= link_to list_path(list),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
        <i class="text-danger fa-solid fa-x fa-xl"></i>
      <% end %>

    </div>
</div>
    <% end %>


</div>

app/views/lists/new.html.erb
<div class="col-6 mx-auto">
  <h1>Create a new list</h1>
  <div>

  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name, class: "form-control" %>
  <%= f.input :details, class: "form-control" %>
  <%= f.submit %>
<% end %>
</div>
<%= link_to "Back to the list", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="mt-3 col-10 mx-auto">
<div class="d-flex justify-content-between">
<div>
  <h1>List: <%= @list.name.capitalize %></h1>
  <p><%= @list.details.capitalize %></p>
  <div class="d-flex flex-wrap">
  <% @bookmarks.each do |bookmark| %>
  <div class="card m-2" style="width: 15rem;">
    <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>">
    <div class="card-body">
      <h3 class="card-title"><%= bookmark.movie.title %></h3>
      <p class="card-text"><%= bookmark.movie.overview %></p>
      <p class="card-text"><% bookmark.movie.rating.times  do %>
        <i class="fa-solid fa-star"></i>
        <% end %>
      </p>
      <blockquote class="blockquote">Critic: <%= bookmark.comment %></blockquote>
      <%= link_to list_bookmark_path(bookmark.list, bookmark),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
      <button class="btn btn-danger rounded text-white align">Delete</button>
      <% end %>
      </div>
    </div>
  <% end %>
  </div>
  </div>
  <div>
  <%= link_to new_list_bookmark_path(@list) do%>
  <button class="btn btn-success text-white rounded">Create a bookmark</button>
  <% end %>
  </div>
</div>

  <%= link_to root_path do%>
  <button class="btn btn-secondary rounded">Back to the list</button>
  <% end %>

</div>